frontend/controllers/RotaryUsersController.php
<?php

namespace frontend\controllers;

use frontend\models\RotaryUsersSearch;
use Yii;
use common\models\RotaryUsers;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class RotaryUsersController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
        ];
    }

    /**
     * @return array
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction'
            ]
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new RotaryUsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new RotaryUsers model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new RotaryUsers();

        try {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                Yii::$app->getSession()->setFlash('success', ['type' => 'success',
                    'duration' => 2000,
                    'icon' => 'fa fa-success',
                    'message' => Yii::t('app', 'User created successfully.'),
                    'positonY' => 'top',
                    'positonX' => 'center'
                ]);

                return $this->redirect(['rotary-users/index']);
            }
        } catch (\Exception $e) {
            Yii::$app->getSession()->setFlash('error', [
                'type' => 'danger',
                'duration' => 3000,
                'icon' => 'fa fa-danger',
                'message' => Yii::t('app', 'Something went wrong. Please try again!'),
                'positonY' => 'top',
                'positonX' => 'center'
            ]);
        }

        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * Updates an existing RotaryUsers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        try {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                if ($model->save()) {
                    Yii::$app->getSession()->setFlash('success', ['type' => 'success',
                        'duration' => 2000,
                        'icon' => 'fa fa-success',
                        'message' => Yii::t('app', 'User updated successfully.'),
                        'positonY' => 'top',
                        'positonX' => 'center'
                    ]);

                    return $this->goHome();
                }
            }
        } catch (\Exception $e) {
            Yii::$app->getSession()->setFlash('error', [
                'type' => 'danger',
                'duration' => 3000,
                'icon' => 'fa fa-danger',
                'message' => Yii::t('app', 'Something went wrong. Please try again!'),
                'positonY' => 'top',
                'positonX' => 'center'
            ]);
        }

        return $this->render('update', [
            'model' => $model
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Throwable
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        try {
            $model->delete();
            Yii::$app->getSession()->setFlash('success', ['type' => 'success',
                'duration' => 2000,
                'icon' => 'fa fa-success',
                'message' => Yii::t('app', 'User deleted successfully.'),
                'positonY' => 'top',
                'positonX' => 'center'
            ]);
        } catch (\Exception $e) {
            Yii::$app->getSession()->setFlash('error', [
                'type' => 'danger',
                'duration' => 3000,
                'icon' => 'fa fa-danger',
                'message' => Yii::t('app', 'Something went wrong. Please try again!'),
                'positonY' => 'top',
                'positonX' => 'center'
            ]);
        }

        return $this->redirect('index');
    }

    /**
     * Finds the RotaryUsers model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return RotaryUsers the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = RotaryUsers::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/views/partials/footer.php
<footer class="main-footer">
</footer>

frontend/views/partials/header-nav.php
<?php

use yii\bootstrap\Html;

?>
<header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">R-Users</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">Rotary Users</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="hidden-xs"><?= Yii::$app->user->identity->name ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <?= Html::a('Profile', '/profile', ['class' => 'btn btn-default btn-flat']) ?>
                            </div>
                            <div class="pull-right">
                                <?= Html::a('Sign out', '/logout', ['class' => 'btn btn-default btn-flat']) ?>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

frontend/views/partials/main-sidebar.php
<?php

use common\models\Contact;
use yii\widgets\Menu;

?>
<aside class="main-sidebar">
    <section class="sidebar">
        <?php
        try {
            echo Menu::widget([
                'items' => [
                    ['label' => '', 'options' => ['class' => 'header']],
                    // Instructor Block
                    ['label' => sprintf('<i class="fa fa-users" aria-hidden="true"></i> <span> %s </span>  <i class="fa fa-angle-left pull-right"></i>', 'Users'),
                        'url' => ['#'],
                        'template' => '<a href="{url}" >{label}<i class="fa fa-angle-left pull-right"></i></a>',
                        'items' => [
                            ['label' => sprintf('<i class="fa fa-plus-circle"></i> %s', 'New user'), 'url' => ['rotary-users/create']],
                            ['label' => sprintf('<i class="fa fa-table"></i> %s', 'List'), 'url' => ['rotary-users/index']],
                        ],
                        'options' => ['class' => 'treeview'],
                    ],
                ],
                'options' => ['class' => 'sidebar-menu', 'data-widget' => 'tree'],
                'submenuTemplate' => "<ul class='treeview-menu'>{items}</ul>",
                'encodeLabels' => false,
                'activateParents' => true,
            ]);
        } catch (Exception $e) {
            Yii::error($e->getMessage(), 'app');
        }
        ?>
    </section>
</aside>